allapps/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
]

oinkoink/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("allapps.core.urls", namespace="core")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

allapps/core/models.py
from django.db import models

# Create your models here.

allapps/core/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, "core/index.html", {})


def about(request):
    return render(request, "core/about.html", {})

templates/_base.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %} | OinkOink - Twitter clone</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
	{% include '_navbar.html' %}
	{% block content %}{% endblock %}

	<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/_navbar.html
{% load static %}
<nav class="navbar">
	<div class="container">
		<div class="navbar-brand">
			<a class="navbar-item" href="{% url 'core:index' %}">
				<img src="{% static 'img/bulma.png' %}" alt="Logo">
			</a>
			<span class="navbar-burger burger" data-target="navbarMenu">
				<span></span>
				<span></span>
				<span></span>
			</span>
		</div>
		<div id="navbarMenu" class="navbar-menu">
			<div class="navbar-end">
				<div class=" navbar-item">
					<div class="control has-icons-left">
						<input class="input is-rounded" type="text" placeholder="Search">
						<span class="icon is-left">
							<i class="fa fa-search"></i>
						</span>
					</div>
				</div>
				{% url 'core:index' as url %}
				<a class="navbar-item {% if request.path == url %}active{% endif %} is-size-5 has-text-weight-semibold"
					href="{% url 'core:index' %}">
					Home
				</a>
				{% url 'core:about' as url %}
				<a class=" navbar-item {% if request.path == url %}active{% endif %} is-size-5 has-text-weight-semibold"
					href="{% url 'core:about' %}">
					About
				</a>
			</div>
		</div>
	</div>
</nav>

templates/core/about.html
{% extends '_base.html' %}

{% block title %}About{% endblock %}

{% block content %}
<h1 class="title">About</h1>
{% endblock %}

templates/core/index.html
{% extends '_base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h1 class="title">Home</h1>
{% endblock %}